replicaCount: 2

image:
  repository: ghcr.io/vuthin-devops-journey/setup-devops
  tag: a707eb1bc4b80ca07c79589a5e7310b68bf9e1e1
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 5000

database:
  host: postgres
  port: "5432"
  secretName: db-secret

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "500m"

probes:
  path: /health

metrics:
  enabled: true
